name: Build Unsigned IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: Build iOS Frameworks
        run: flutter build ios --no-codesign --release
      - name: Create IPA Structure
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r Unsigned-IPA.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: Unsigned-IPA-Client
          path: Unsigned-IPA.ipa
