name: Build Unsigned IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build IPA
        run: flutter build ios --no-codesign --release
      - name: Prepare Artifact
        run: |
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r Unsigned-IPA.ipa Payload
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: Unsigned-IPA
          path: build/ios/iphoneos/Unsigned-IPA.ipa
